=== 52North/WPS/52n-wps-webapp/src/main/webapp/config/schema_v2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://n52.org/wps" xmlns:gml="http://www.opengis.net/gml/3.2" targetNamespace="http://n52.org/wps">
	<xs:simpleType name="T_Property">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	<xs:element name="WPSConfiguration">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Datahandlers"/>
				<xs:element ref="AlgorithmRepositoryList"/>
				<xs:element ref="RemoteRepositoryList"/>
				<xs:element ref="Server"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Server">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Property" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="Database" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="hostname" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="hostport" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="includeDataInputsInResponse" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:boolean"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="computationTimeoutMilliSeconds" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="cacheCapabilites" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:boolean"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="webappPath" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="repoReloadInterval" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:double"/>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Repository">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="Property" minOccurs="0" maxOccurs="unbounded"/>
			</xs:choice>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="className" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="active" type="xs:boolean" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Property">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="T_Property">
					<xs:attribute name="name" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string"/>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="active" type="xs:boolean" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="Format">
		<xs:complexType>
			<xs:attribute name="mimetype" type="xs:string" use="optional"/>
			<xs:attribute name="schema" type="xs:string" use="optional"/>
			<xs:attribute name="encoding" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="ParserList">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Parser" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Parser">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Format" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="Property" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="className" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="active" type="xs:boolean" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="GeneratorList">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Generator" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Generator">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Format" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="Property" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="className" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="active" type="xs:boolean" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Datahandlers">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ParserList"/>
				<xs:element ref="GeneratorList"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Database">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Property" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Algorithm">
		<xs:complexType>
			<xs:attribute name="className" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="AlgorithmRepositoryList">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Repository" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="RemoteRepositoryList">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="RemoteRepository" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="RemoteRepository">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="Property" minOccurs="0" maxOccurs="unbounded"/>
			</xs:choice>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="active" type="xs:boolean" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== 52North/WPS/52n-wps-r/src/test/resources/test_wps_config_r.xml
<?xml version="1.0" encoding="UTF-8"?>
<WPSConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://n52.org/wps schema_v2.xsd" xmlns="http://n52.org/wps">
	<AlgorithmRepositoryList>
		<Repository name="RAlgorithmRepository"
			className="org.n52.wps.server.spring.SpringWrapperAlgorithmRepository"
			active="true">
			<Property active="true" name="wrappeeName">org.n52.wps.server.r.LocalRAlgorithmRepository
			</Property>
		</Repository>
		<Repository name="LocalRAlgorithmRepository"
			className="org.n52.wps.server.r.LocalRAlgorithmRepository" active="false">
			<Property name="R_enableBatchStart" active="true">true</Property>
			<Property name="R_datatypeConfig" active="true">R/R_Datatype.conf
			</Property>
			<Property name="R_wdStrategy" active="true">default</Property>
			<Property name="R_wdName" active="false">myName</Property>
			<Property name="R_resourceDirectory" active="true">R/resources
			</Property>
			<Property name="R_RserveHost" active="true">localhost</Property>
			<Property name="R_RservePort" active="true">6311</Property>
			<Property name="R_RserveUser" active="false">NA</Property>
			<Property name="R_RservePassword" active="false">NA</Property>
			<Property name="R_scriptDirectory" active="true">R/scripts
			</Property>
			<Property name="R_utilsScriptDirectory" active="true">R/utils;org/n52/wps/R/unzipRenameFile.R;org/n52/wps/R/wpsStatus.R
			</Property>
			<Property name="R_cacheProcesses" active="true">true</Property>
			<Property name="R_session_memoryLimit" active="true">1000
			</Property>
			<Property name="Algorithm" active="true">org.n52.wps.server.r.test.calculator
			</Property>
		</Repository>
		<Repository name="ServiceLoaderAlgorithmRepository"
			className="org.n52.wps.server.ServiceLoaderAlgorithmRepository"
			active="true">
		</Repository>
	</AlgorithmRepositoryList>

	<Server hostname="localhost" hostport="8080"
		includeDataInputsInResponse="false" computationTimeoutMilliSeconds="5"
		cacheCapabilites="false" webappPath="wps" repoReloadInterval="0">
		<!-- Setting to 'true' will enable filtering of responses documents. Any 
			server URL in the response document will be replaced with the server URL 
			used in the HTTP request. -->
		<Property name="responseURLFilterEnabled" active="true">false
		</Property>
		<Database>
			<!-- NOTE: database wipe is only implemented for the FlatFileDatabase 
				(the default) -->
			<!-- enable database wiping base on values below -->
			<Property name="wipe.enabled" active="true">true</Property>
			<!-- scans database every 1 hour -->
			<Property name="wipe.period" active="true">PT1H</Property>
			<!-- deletes files older than 7 days -->
			<Property name="wipe.threshold" active="true">P7D</Property>
			<!-- save complex values gzipped -->
			<Property name="complex.gzip" active="true">true</Property>
		</Database>
	</Server>
</WPSConfiguration>
